# Generated by Django 6.0 on 2026-01-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Field Type',
                'verbose_name_plural': 'Field Types',
            },
        ),
        migrations.CreateModel(
            name='FieldPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_label', models.CharField(max_length=200)),
                ('default_help_text', models.CharField(blank=True, max_length=300)),
                ('default_validations', models.JSONField(default=dict)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.fieldtype')),
            ],
            options={
                'verbose_name': 'Field Preset',
                'verbose_name_plural': 'Field Presets',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('conditional_logic', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('validations', models.JSONField(blank=True, default=dict)),
                ('field_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.fieldtype')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.fieldpreset')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
            },
        ),
        migrations.CreateModel(
            name='FormFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField()),
                ('action', models.JSONField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formfield', verbose_name='form field')),
            ],
            options={
                'verbose_name': 'Form Field Rule',
                'verbose_name_plural': 'Form Field Rules',
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form', verbose_name='form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
            },
        ),
        migrations.CreateModel(
            name='FormFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formfield', verbose_name='form field')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formresponse', verbose_name='form response')),
            ],
            options={
                'verbose_name': 'Form Field Response',
                'verbose_name_plural': 'Form Field Responses',
            },
        ),
        migrations.CreateModel(
            name='ValidationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('parameter_schema', models.JSONField()),
                ('default_error_message', models.CharField(max_length=200)),
                ('applicable_field_types', models.ManyToManyField(to='forms.fieldtype')),
            ],
            options={
                'verbose_name': 'Validation Type',
                'verbose_name_plural': 'Validation Types',
            },
        ),
    ]
