# Generated by Django 6.0 on 2026-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_alter_fieldchoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="widths",
            field=models.JSONField(
                blank=True,
                default={"2xl": 2, "lg": 3, "md": 4, "sm": 6, "xl": 2, "xs": 12},
            ),
        ),
    ]
