# Generated by Django 6.0 on 2026-01-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formfield_widths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='widths',
        ),
    ]
