# Generated by Django 6.0 on 2026-01-08 13:12

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formfield_widths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfieldgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='formfieldgroup',
            name='order',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='widths',
            field=models.JSONField(blank=True, default=forms.models.create_default_widths_dict),
        ),
        migrations.AlterField(
            model_name='formfieldchoicemembership',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
