# Generated by Django 6.0 on 2026-01-08 13:13

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_formfieldgroup_options_remove_formfield_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='order',
            field=models.JSONField(blank=True, default=forms.models.create_default_order_dict),
        ),
        migrations.AddField(
            model_name='formfieldgroup',
            name='order',
            field=models.JSONField(blank=True, default=forms.models.create_default_order_dict),
        ),
    ]
