# Generated by Django 6.0 on 2026-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formfield_order_formfieldgroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='optional',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
